### ISSUE TITLE
NPM Package Should Be ES5 Not ES6

### ISSUE THREAD

**Issue by marcusrbrown** [chainpoint/chainpoint-client-js#1]
The Chainpoint Client library currently ships with a ES6 module (index.js). Some browsers support ES6 (or a subset), but the majority still ship with ES5 support. At build time, [babelify](https://github.com/babel/babelify) or similar should be used with browserify to transpile chainpoint-client from ES6 to ES5, and the ES5 version of index.js should be published to NPM.

Note that you can ship ES6 alongside ES5 by using the "module" parameter in package.json.

**Comment by grempe** [comment]
Thanks for the feedback. We'll look into this for the next version.

**Comment by grempe** [comment]
FYI, we've pushed v0.1.2 with the experimental tag which provides bundles for both node and the web. Feel free to give it a go as we prep to release this soon.

**Comment by grempe** [comment]
Version 0.1.2 with new bundling is pushed to npmjs.org. I'm going to close this issue as it should be fully addressed by the new bundles. Please feel free to comment if you encounter any issues.

Thanks.
