### ISSUE TITLE
getNodes silently failing / timing out

### ISSUE THREAD

**Issue by rjaus** [chainpoint/chainpoint-client-js#2]
Hey team,

This client has been working well up until now.  But it appears there is currently an issue with the DNS auto discovery, which is leading to getNodes timing out.  The issue is, it fails silently.  

The submitHashes function eventually returns an empty array. (due to getNodes call failing)

Calling getNodes directly has the same effect.  Hangs until finally returning no nodes.

Suggest setting an explicit timeout on getNodes and raising an error / promise rejection when it's reached, that way it's catchable.

**Comment by rjaus** [comment]
<img width="265" alt="screen shot 2018-02-22 at 1 03 19 pm" src="https://user-images.githubusercontent.com/773626/36516150-c8905688-17d0-11e8-929f-e960da0fe7fa.png">

Note: it is returning as a rejection, but it returns a blank array.

**Comment by grempe** [comment]
Thanks for the report. We experienced a DB issue that manifested itself in the way you described. I will leave this issue open though so we can take a look at your suggestion regarding timeout and raise of an error.

Cheers.

**Comment by grempe** [comment]
A fix for this issue has been pushed. It adds a timeout to the HTTP connections.

Version 0.1.1 of chainpoint-client-js has been pushed to NPM. https://www.npmjs.com/package/chainpoint-client
