### ISSUE TITLE
v3 receipt verification

### ISSUE THREAD

**Issue by auriga1** [chainpoint/chainpoint-client-js#31]
Hi,
i'm trying to get the proof of a v3 receipt but I can't figure out how to proceed.
What I want to do is, starting from my hash, to combine left and right leaves to obtain the merkle tree root.

I've search on your code but it's minified.

Any help would be appreciated.

**Comment by bucko13** [comment]
Hi @auriga1,

For searching the code, the minification just comes from the [index.js](https://github.com/chainpoint/chainpoint-client-js/blob/master/index.js) file so you can try and walk through the code there if you're curious. There is also an in-progress branch in preparation for a version 2 of the chainpoint protocol that has the library completely refactored and modularized which should hopefully make it easier to browse (including tests to get a better understanding of what's going on under the hood). You can see that branch [here](https://github.com/chainpoint/chainpoint-client-js/tree/core-v2-support).

As for the question about verification, I'm not entirely clear on what you're trying to do. Is this just a question about how the proof verification works? If you have the v3 proof already then you can verify that with this library directly with the `verify` method. If you're trying to figure out how that code works and do it manually, then you're on the right track in terms of getting the merkle root. If you use the `evaluate` method, it will parse the proof and get the `expected_value` which is the merkle root that `verify` checks against the bitcoin blockchain (or chainpoint calendar for calendar proofs). You can also use the [chainpoint-cli](https://github.com/chainpoint/chainpoint-cli) for testing this. 

Hope this helps! Let me know if anything isn't clear.

**Comment by auriga1** [comment]
Thank you very much,
I found the solution reading chainpoint-parse code.
