### ISSUE TITLE
Anchor to ETH

### ISSUE THREAD

**Issue by pvanroos** [chainpoint/chainpoint-client-js#6]
Are there any examples of anchoring to ETH?

**Comment by grempe** [comment]
Thanks for the question! At this time we anchor to the Bitcoin public Blockchain only.

**Comment by pvanroos** [comment]
Ok.  Why does Chainpoint Proof Version 3.0 show ETH as a possible anchor then?  Is that planned for the future?

**Comment by grempe** [comment]
Yes, we have designated a variable in the Chainpoint Proof v3 format for anchoring to `eth` if that is what you are referring to. As I stated earlier though, at this point in time we only anchor to the Bitcoin public blockchain. Anchoring to Ethereum is something we may provide in the future. Do you have a specific case where anchoring to one chain vs. the other would be significant for you or offer a different benefit?

**Comment by pvanroos** [comment]
Yep.  That's what I'm referring to.  

Actually, I should ask you that question.  Why put it in the public specification?  I'm guessing that somebody on your team thought it might be valuable. @jasonbukowski   Why don't we ask them why they thought users might want to anchor to ETH?

**Comment by grempe** [comment]
Well @jasonbukowski, @waynevaughan, and I wrote the v3 spec together. So its safe to ask me. ;-)

We put it there as we will likely anchor to Ethereum eventually. There is no announced timetable for doing so though.

I am curious though as to what benefit you feel you would get from an anchor that is tied to both a Bitcoin block and an Ethereum block. Do you feel it would provide you with a specific benefit? This is the type of feedback that will help us decide whether this is something we want to prioritize.

Cheers.

**Comment by pvanroos** [comment]
@grempe 

Sorry. Not trying to be argumentative.  I'm trying to understand from a higher level the implications and risk of having the proofs anchored on btc only  (not necessarily true since it's anchored initially to the cal).  

We are building a solution entirely on eth (so essentially we're using smart contracts, DApps, tokens and other features of the platform).  We'd like to integrate Chainpoint Proofs into our workflows.  My initial thinking (and I admit it may be flawed) is that having most of our solution on the eth chain (including the Chainpoint proof) is more advantageous.  

That being said, the Chainpoint node takes care of retrieving the proof using the verify command, so perhaps my understanding is wrong.  In the full white paper (https://tokensale.tierion.com/TierionTokenSaleWhitePaper.pdf), the document is replete with references to eth as a possible anchor but there's no examples of being able to specify the anchor "target" in the submit command for example.  But are you suggesting I not worry about where the proof was anchored--as long as it was anchored to at least the cal?

**Comment by grempe** [comment]
> Sorry. Not trying to be argumentative. I'm trying to understand from a higher level the implications and risk of having the proofs anchored on btc only (not necessarily true since it's anchored initially to the cal).

Not taken as argumentative. Just trying to answer and understand your concerns.

> We are building a solution entirely on eth (so essentially we're using smart contracts, DApps, tokens and other features of the platform). We'd like to integrate Chainpoint Proofs into our workflows. My initial thinking (and I admit it may be flawed) is that having most of our solution on the eth chain (including the Chainpoint proof) is more advantageous.

I'm not sure that the fact that your platform uses Ethereum will be advantageous one way or another in relation to our Chainpoint proofs. The integration with Chainpoint is through client libraries or direct HTTP calls to Nodes in our network. If in the future we did integrate with Ethereum it would be as an additional anchor in the proof in addition to, not in place of, anchoring to Bitcoin and our Calendar. This is one of the reasons we have hesitated in providing it, as it would increase the size of all proofs, for perhaps limited security gains.

> That being said, the Chainpoint node takes care of retrieving the proof using the verify command, so perhaps my understanding is wrong.

To clarify, it is the responsibility of the client to retrieve the proof from a Node (and retain permanent custody of it) using the `GET /proofs/:uuid` endpoint on the same Node you submitted the hash to.

Verification of the proof can be done by calling `POST /verify` on *any* Node in the world with the Proof in the POST body. Alternatively, we provide a Javascript library which can parse the proof locally and present you with the expected Merkle root of the Bitcoin block that the proof claims to be anchored to. You can verify that independently of us with any Bitcoin full node or block explorer.

Example:
https://runkit.com/tierion/verify-a-chainpoint-proof-directly-using-bitcoin

> But are you suggesting I not worry about where the proof was anchored--as long as it was anchored to at least the cal?

I would suggest that as long as you retrieve the full Bitcoin proof (takes ~90m to generate) that you have a permanent proof that you can independently verify. The cal proof requires that you trust us to some degree. The Bitcoin proof provides the highly secure (long term) variant.

Cheers.

**Comment by pvanroos** [comment]
I understand better now.  Great response and very informative.  I appreciate it.  I'm very excited about where you're going with this technology.  Thanks @grempe

**Comment by grempe** [comment]
My pleasure. Best of luck with your venture and integration with Chainpoint!
