### ISSUE TITLE
dns.resolveTxt() returns ESERVFAIL

### ISSUE THREAD

**Issue by aptuzz** [chainpoint/chainpoint-client-js#9]
Experienced this when trying to use the package in a Google Cloud Function (was working fine locally).
It looks like the query should be performed on the authoritative NS, or risks failing depending on DNS used for resolution.

See the related StackOverflow question/response:
https://stackoverflow.com/questions/54081504/cloud-functions-dns-resolvetxt-returns-eservfai

Code reference:
https://github.com/chainpoint/chainpoint-client-js/blob/02019686f30935f2db2c53f9bebf7a381afd5896/index.js#L100

**Comment by michael-iglesias** [comment]
@cementito According to the StackOverflow thread, it looks like you were able to resolve the issue. When you have a moment can you provide a solution in StackOverflow for the rest of the community?

Thanks!
